server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-security-keycloak
            client-secret:
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/th
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/th